### ISSUE TITLE
Just a question...

### ISSUE THREAD

**Issue by nabilcreates** [cheeaun/arrivelah#2]
using one of your api's can i just get the bus stop name from just the bus stop code. I have been trying to create a mobile app using your Datamall proxy. Thanks, you really did help me alot!

I thought of a json that looked like this:
`{
    "27301": "Blk 978"
}`

**Comment by nabilcreates** [comment]
I realised what the problem was, but instead, i got a better idea. A proxy where there is the parameters behind. it will look something like: `https://busstopcode.idk/?id=27301` and it will return the bus stop info including the name. I am not sure if LTA Datamall has implemented this

**Comment by cheeaun** [comment]
@renabil LTA Datamall has an endpoint for bus stops, but returns *all* bus stops instead of one at a time. You can try that instead. By right, if you have a list of bus stop codes on your side, you should already have the names.

**Comment by nabilcreates** [comment]
Its alright, i got it to work with .filter() and .match() so that it will return a specific array that contains that bus stop info. Thanks! :)
