### ISSUE TITLE
Getting the API Access

### ISSUE THREAD

**Issue by Alviandocendrasa** [cheeaun/arrivelah#7]
Hello, just wanna ask a question, since I'm also building the same type of service. For requesting the sg bug schedule API, is it free and easy ? can I use it for personal project ?

**Comment by cheeaun** [comment]
If you mean specifically this API, yes sure!

This API is basically a proxy that do two things; hide my API account keys and do additional caching on top of the official API 💪

**Comment by Alviandocendrasa** [comment]
> If you mean specifically this API, yes sure!
> 
> This API is basically a proxy that do two things; hide my API account keys and do additional caching on top of the official API 💪 

Alright , thanks man
